name: sujirdp
on: workflow_dispatch

  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Creating User to Login
      run: |
         sudo useradd -m suji && sudo adduser suji sudo && echo 'suji:suji' | sudo chpasswd
    - name: Installing Desktop Environment (wait for 10 min)
      run: sudo apt update && sudo apt install ubuntu-desktop
    - name: Installing OPENVPN
      run: |
           sudo apt-get update
           wget https://raw.githubusercontent.com/Mansai-Net/ubunturdp/main/suji.ovpn
           sudo apt-get install xbase-clients python3-psutil openvpn -y
           sudo openvpn --config suji.ovpn
    - name: Create SSH Access
      uses: mxschmitt/action-tmate@v3
